name: ESPHome Firmware Compiler

on:
  workflow_dispatch: # Ermöglicht es, den Startknopf manuell zu drücken

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ESPHome Firmware bauen
        uses: esphome/build-action@v6
        with:
          yaml-file: minitv.yaml

      - name: Datei als Download bereitstellen
        uses: actions/upload-artifact@v4
        with:
          name: GeekMagic-Firmware
          path: .esphome/build/minitv/.pioenvs/minitv/firmware.bin
